FEATURES = {
    'special_char': 'Number of Speicial Character in URL like ~,!,@,#,$,%,^,&,*,...',
    'have_ip': 'Checks if IP address in URL',
    'have_at': 'Checks the presence of @ in URL',
    'url_length': 'Finding the length of URL and categorizing',
    'url_depth': 'Gives number of / in URL',
    'redirection': 'Checking for redirection // in the URL',
    'port_in_url': 'Suspicous port appear in the URL',
    'use_http': 'Use HTTP insted of HTTPS',
    'http_in_domain': 'HTTP(S) in the URL (example: https://report?https://reportId=https://QYJT9PC9YPFTDC7JJ&https://reportType=https://question)',
    'tiny_url': 'Checking for Shortening Services in URL',
    'prefix_suffix': 'Checking for Prefix or Suffix Separated by (-) in the URL',
    'dns_record': 'Check if the DNS record A point to the right Website',
    'domain_lifespan': 'Checking if Life span of domain under 6 months',
    'domain_timeleft': 'Checking if time left of domain under 6 months',
    'same_asn': 'Check if others server like Domain, Dns Server,... on the same IP',
    'iframe': 'Check if Iframe Function in Web content',
    'mouse_over': 'Check if mouse_over Function in Web content',
}
